---
abstract: 'DBI::Profile panel'
author:
  - 'Tim Bunce <Tim.Bunce@pobox.com>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102345, CPAN::Meta::Converter version 2.101610'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-Debug-DBIProfile
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
requires:
  DBI::Profile: 0
  Plack::Middleware::Debug: 0.10
  Plack::Util::Accessor: 0
  Time::HiRes: 0
  parent: 0
  perl: 5.008
resources:
  homepage: http://github.com/timbunce/Plack--Middleware--Debug--DBIProfile/tree
  repository: git://github.com/timbunce/Plack--Middleware--Debug--DBIProfile.git
version: 0.102
